// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2BF7Fv2-Gr2OWcWBi-0Osimx2o5gcNhQ',
    appId: '1:920338196243:web:52dd05ecedecc154599ce6',
    messagingSenderId: '920338196243',
    projectId: 'angular-amp-152011',
    authDomain: 'angular-amp-152011.firebaseapp.com',
    databaseURL: 'https://angular-amp-152011-default-rtdb.firebaseio.com',
    storageBucket: 'angular-amp-152011.appspot.com',
    measurementId: 'G-HC2GNFJ21K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhs9oEinfDIFTQznJrJtKQzARMKChkN78',
    appId: '1:920338196243:android:f0a8f90e25a63c9e599ce6',
    messagingSenderId: '920338196243',
    projectId: 'angular-amp-152011',
    databaseURL: 'https://angular-amp-152011-default-rtdb.firebaseio.com',
    storageBucket: 'angular-amp-152011.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbzVVqQHyOLhgsBSy8pcdfkY60kkrDBtM',
    appId: '1:920338196243:ios:bfea85058353ea90599ce6',
    messagingSenderId: '920338196243',
    projectId: 'angular-amp-152011',
    databaseURL: 'https://angular-amp-152011-default-rtdb.firebaseio.com',
    storageBucket: 'angular-amp-152011.appspot.com',
    iosBundleId: 'com.example.hipsterassignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbzVVqQHyOLhgsBSy8pcdfkY60kkrDBtM',
    appId: '1:920338196243:ios:bfea85058353ea90599ce6',
    messagingSenderId: '920338196243',
    projectId: 'angular-amp-152011',
    databaseURL: 'https://angular-amp-152011-default-rtdb.firebaseio.com',
    storageBucket: 'angular-amp-152011.appspot.com',
    iosBundleId: 'com.example.hipsterassignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2BF7Fv2-Gr2OWcWBi-0Osimx2o5gcNhQ',
    appId: '1:920338196243:web:a334888f148255e7599ce6',
    messagingSenderId: '920338196243',
    projectId: 'angular-amp-152011',
    authDomain: 'angular-amp-152011.firebaseapp.com',
    databaseURL: 'https://angular-amp-152011-default-rtdb.firebaseio.com',
    storageBucket: 'angular-amp-152011.appspot.com',
    measurementId: 'G-QCDZ8HVQDQ',
  );
}
